steps:
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=960eb824c3c39045e47da57825878342775a5af5'
    - '-Dsonar.projectKey=canbahadir_cloud-native-challenges'
    - '-Dsonar.organization=canbahadir'
    - '-Dsonar.sources=.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-app-$BUILD_ID', 'task3/dockerapp']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/node-app-$BUILD_ID']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --app=node-app-green
    - --image=gcr.io/$PROJECT_ID/node-app-$BUILD_ID
    - --location=us-central1-c
    - --cluster=jenkinscluster
tags: ['cloud-builders-community']
