steps:
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=960eb824c3c39045e47da57825878342775a5af5'
    - '-Dsonar.projectKey=canbahadir_cloud-native-challenges'
    - '-Dsonar.organization=canbahadir'
    - '-Dsonar.sources=.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-app-$BUILD_ID', 'task3/dockerapp']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/node-app-$BUILD_ID']
  - name: 'gcr.io/$PROJECT_ID/helm'
    args: ['upgrade', '--cleanup-on-fail', 'nodeapp', 'task4/helm-chart/', '--set', 'image.repository=gcr.io/$PROJECT_ID/node-app-$BUILD_ID']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=jenkinscluster'
tags: ['cloud-builders-community']
