all:
  hosts:
    node1:
      ansible_host: <External IP of server Master0>
      ip: <Internal IP of server Master0>
    node2:
      ansible_host: <External IP of server Master1>
      ip: <Internal IP of server Master1>
    node3:
      ansible_host: <External IP of server Master2>
      ip: <Internal IP of server Master2>
    node4:
      ansible_host: <External IP of server Worker0>
      ip: <Internal IP of server Worker0>
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
